In [25]:
import numpy as np
import pandas as pd

Creating data frame

In [26]:
data = {

   "Name": ["Rahul", "Priya", "Arjun", "Sneha", "Rohan"],

   "Age": [22, 25, 21, 28, 24],

   "City": ["Kolkata", "Mumbai", "Delhi", "Bangalore", "Pune"],

   "Salary": [35000, 50000, 30000, 65000, 45000]

}

In [27]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data,columns =columns)
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

Selection and Indexing of Columns

In [29]:
df2[["Name","City"]]

    Name       City
0  Rahul    Kolkata
1  Priya     Mumbai
2  Arjun      Delhi
3  Sneha  Bangalore
4  Rohan       Pune

Creating a new column

In [41]:
df2["Designation"] = ["Doctor","Eng.","Professor","Developer","Plumber"]

In [42]:
df2

    Name  Age       City  Salary Designation
0  Rahul   22    Kolkata   35000      Doctor
1  Priya   25     Mumbai   50000        Eng.
2  Arjun   21      Delhi   30000   Professor
3  Sneha   28  Bangalore   65000   Developer
4  Rohan   24       Pune   45000     Plumber

Removing Columns

In [ ]:
df2.drop("Designation",axis=1)  #axis 1 is column and axis 0 is row by deafult pandas take axis=0 if not explicitly mentioned

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

In [44]:
df2.drop("Designation",axis=1,inplace=True) #inplace means drop from original data base

In [47]:
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

In [ ]:
#removing from row 

df2.drop(0) #1st row got deleted as 0 means 1st row

    Name  Age       City  Salary
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

In [52]:
df2.drop(4)

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000

In [54]:
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

Selecting Rows

In [ ]:
df2.loc[0] #seleting 1st row

Name        Rahul
Age            22
City      Kolkata
Salary      35000
Name: 0, dtype: object

In [63]:
df2.loc[[0,2]] #seleting 1st row and 3rd row

    Name  Age     City  Salary
0  Rahul   22  Kolkata   35000
2  Arjun   21    Delhi   30000

In [ ]:
df2.iloc[3] #explicitly mentioned to select index 3 if there was not mentioned the index then this helps

Name          Sneha
Age              28
City      Bangalore
Salary        65000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [65]:
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

In [66]:
# Q1  GIVE THE third and 4th row's ,city and salary

In [70]:
df2.loc[[3,4]] [["City","Salary"]]

        City  Salary
3  Bangalore   65000
4       Pune   45000

In [71]:
df2.loc[[0,1]][["City","Salary"]]

      City  Salary
0  Kolkata   35000
1   Mumbai   50000

Conditional Selection

In [72]:
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000

In [ ]:
# Q1) I WANT THE PEOPLES WHOSE AGE IS ABOVE 25 OR EQUAL

In [75]:
df2[df2["Age"]>=25]

    Name  Age       City  Salary
1  Priya   25     Mumbai   50000
3  Sneha   28  Bangalore   65000

In [76]:
# Q2) I WANT THE PEOPLES WHOSE AGE IS ABOVE 25 OR EQUAL AND LIVES IN MUMBAI

In [77]:
df2[(df2["Age"]>=25) & (df2["City"]=="Mumbai")]

    Name  Age    City  Salary
1  Priya   25  Mumbai   50000

#Q2 I WANT THE PEOPLES WHOSE AGE IS ABOVE 25 OR EQUAL AND LIVES IN KOLKATA

In [ ]:
df2[(df2["Age"]>=25) & (df2["City"]=="Kolkata")]  #empty list came as there is noone is above or equal 25

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [80]:
df2

    Name  Age       City  Salary
0  Rahul   22    Kolkata   35000
1  Priya   25     Mumbai   50000
2  Arjun   21      Delhi   30000
3  Sneha   28  Bangalore   65000
4  Rohan   24       Pune   45000